### ISSUE TITLE
User profile - first aproach.

### ISSUE THREAD

**Issue by vmariano** [d-cent/democracyos#35]
In the first version will be do the basic info of the user with edit button if is the profile of the logged user.
![img_5602](https://cloud.githubusercontent.com/assets/796960/4153476/14c667ae-3459-11e4-9d72-9780727e63ff.JPG)

Related to #5

**Comment by vmariano** [comment]
- The user profile should be available on  `user/<user id>`
- My user profile should be available on  `user/me`
  - If i'm looking my options, we show a button/link to change my settings.
- Options over user profile should be changed over the user settings.
- We add `about me` and `following tags` as new user settings.

**Comment by gvilarino** [comment]
:+1:
