### ISSUE TITLE
User profile - editable options

### ISSUE THREAD

**Issue by vmariano** [d-cent/democracyos#39]
For the moment some user options are editable in the section  `settings`. The user should be able to edit in the same place where is see the user profile.

Also, we must remove that options from settings.

This options are:
- Name
- Last name
- About
- Tags
- Avatar

This is related to #35 and #5

**Comment by gvilarino** [comment]
This should include removing options from `/settings` once they're mirated to `profile`

**Comment by gvilarino** [comment]
We should add, before finishing:
- [x] Add a title over Activity Stream (with that text).
- [x] Remove underline on mouse over for labels and titles.
- [x] Show 'Your profile was successfuly updated' right above.
- [x] Navigate back to the normal profile page after saving changes.

**Comment by piamancini** [comment]
Add URL for profile pic (bring from DOS)
Style tags and general look&feel similar to 
![screen shot 2014-09-22 at 3 47 25 pm](https://cloud.githubusercontent.com/assets/3671070/4361937/ed2b1418-4288-11e4-9773-78e0fc7653fb.png)
