### ISSUE TITLE
Link tasks to Guanyem user story and add missing ones

### ISSUE THREAD

**Issue by jaakkokorhonen** [d-cent/democracyos#42]
@gvilarino, @jayapapaya do you know enough to do this?
I hear this has been lifted in priority by Fancesca to be the first case.

**Comment by jayapapaya** [comment]
More or less, enough to start anyway, and I am assuming we will be getting a clearer idea as we progress, and in communication with Toret.

**Comment by jaakkokorhonen** [comment]
done
