### ISSUE TITLE
Upload user images

### ISSUE THREAD

**Issue by nestadcent** [d-cent/democracyos#44]

**Comment by jaakkokorhonen** [comment]
Does this refer to profile picture images? Could we live through the pilot with users posting an url of their picture?

**Comment by nestadcent** [comment]
yes is profile picture images. They find gravatar too complicated. I think if we also have twitter sign in (as option) is going to be ok, otherwise users should be able to upload their pictures

**Comment by nestadcent** [comment]
As for other images, I think now admin can already post general images next to main text, right?

**Comment by jaakkokorhonen** [comment]
@piamancini how did it turn out with this?

**Comment by gvilarino** [comment]
@jaakkokorhonen @nestadcent we now allow users to put a URL where to fetch their image. This is still not uploading, but they can copypaste any of their existing avatars' URL and they'd have it solved. Uploading and storage handling is a whole different story and effort.

**Comment by jaakkokorhonen** [comment]
@gvilarino great! can you provide a sample and close the task?

**Comment by gvilarino** [comment]
Navigate to http://demo.democracyos.org/settings

Yo need be logged in.

**Comment by jaakkokorhonen** [comment]
That's nice.
![screenshot 2014-10-04 01 26 48](https://cloud.githubusercontent.com/assets/3482497/4513391/7247b93c-4b4c-11e4-9b80-604d27416250.png)
