### ISSUE TITLE
Make admin page more user-friendly

### ISSUE THREAD

**Issue by jayapapaya** [d-cent/democracyos#47]
Ask Toret for more info on whether this also entails functionality, or only UI design issues.

**Comment by jaakkokorhonen** [comment]
Admin-page for inputting content is to be made redundant for d-cent, since whoever user is data owner, publishes it. Not the node admin. Was there a specific problem in the current ui that prevents us from piloting?

**Comment by jaakkokorhonen** [comment]
@jayapapaya so please can we have more specifically, which components are causing negative experience?

**Comment by gvilarino** [comment]
@jaakkokorhonen we would really like to make it better and have been discussing some enhancements to this. We actually already made some tiny improvements like better handling error/success messaging but I belive this is a major thing the app needs.

I'd say the on-premises edition approach github provides is the way to go. Admins shouldn't need to go to a diferent area for uploding new topics; they should be able to do it on the same UI as topics are displayed, and be able to edit everything on the same UI.
