### ISSUE TITLE
Complete Catalan translation

### ISSUE THREAD

**Issue by jayapapaya** [d-cent/democracyos#49]

**Comment by jaakkokorhonen** [comment]
@gvilarino which files contain the language texts?

**Comment by sachalifs** [comment]
lib/translations/lib/ca.json

**Comment by jaakkokorhonen** [comment]
cheers

**Comment by jaakkokorhonen** [comment]
So who knows both Catalan and English to translate https://github.com/d-cent/democracyos/blob/development/lib/translations/lib/ca.json? @arnaumonty any ideas?

**Comment by gvilarino** [comment]
We're already working on this with Toret's team.

**Comment by jaakkokorhonen** [comment]
Ok so who will test and approve Catalan texts in between the 6th and 10th of October?

**Comment by gvilarino** [comment]
I will upload them as soon as Toret sends me the content. Testing will be up to him and his team. I'm responsible for this.

**Comment by geraldo** [comment]
Just commited completed catalan translation to our fork: https://github.com/GuanyemBarcelona/democracyos/blob/development/lib/translations/lib/ca.json
