### ISSUE TITLE
LIST of items to simplify for the Guanyem pilot on the 11th

### ISSUE THREAD

**Issue by jayapapaya** [d-cent/democracyos#52]

**Comment by jayapapaya** [comment]
@gvilarino  - I don't know if you saw Jaakko's question on Slack, but am putting together a list of some simplifications for the DOS interface - in case it will take too long to implement the UI designed by the Finish people. It is important that we strip down the design for the Guanyem pilot so that we have them focus more on feedback for the functionality than on UI for now. Let me know if its cool for you guys to implement this next week if the patternlab stuff is not possible ...

**Comment by jayapapaya** [comment]
Here are some quick sketches - will write up css changes for these to make it quick. Its mainly just replacing fonts, simplifying color scheme and changing the icon. 

![dos_simple01](https://cloud.githubusercontent.com/assets/5570486/4505748/250f52ee-4afa-11e4-8d1a-3ee0f7a79615.png)
![dos_simple02 fw](https://cloud.githubusercontent.com/assets/5570486/4505750/2518c388-4afa-11e4-82c2-df90b334e548.png)
![dos_simple03](https://cloud.githubusercontent.com/assets/5570486/4505749/2518934a-4afa-11e4-9cd9-7577e4939009.png)

**Comment by gvilarino** [comment]
thanks @jayapapaya 

For things like this we would need you to provide all css changes explicitly specified, fonts, truetype fonts and whatever else so we don't waste time re-doing your work.

Also, the guanyem logo as tag icon is something tricky because we use a font generated throug a script from SVGs.

**Comment by jaakkokorhonen** [comment]
@jayapapaya we need a list of things that are to be either 
1) hidden or 
2) overwritten with something that is published in patterns.

For new items to be overwritten, add a task to https://github.com/d-cent/patterns/issues with the tag "css" or "js", respectively. 

Moreover, can you create a one-colored, transparent, guanyem SVG?

To match the deadline given by Guanyem, these will need to be done on monday latest, so they can be implemented by DOS or Frantic team by Tuesday/Wednesday.

**Comment by jayapapaya** [comment]
@jaakkokorhonen  cool, will have that ready Monday, no prob.

@gvilarino yep these will all come by Monday. Will get an svg from the guanyem logo over to you too.

Thanks guys!

**Comment by jaakkokorhonen** [comment]
@jayapapaya so was there a list of things to hide?

**Comment by jaakkokorhonen** [comment]
@gvilarino make sure https://github.com/d-cent/patterns/labels/css is specified to your liking. 
There is very little time for extra iteration rounds.

**Comment by jayapapaya** [comment]
@jaakkokorhonen  - kind of hard to say, given that currently a lot of changes have happened in the d-cent instance rather than the guanyem, so am not 100% certain what will be pushed to the guanyem fork. @gvilarino maybe we can communicate about that tomorrow briefly? I think you have been in touch w Toret quite a bit about functionality, so am not going to mess w that.
- Also, quick thought, don't know what/if there is any agreement on adding D-CENT/ DOS logos and links to the pilot. 

If these should remain, they should simply be top left corner, where they currently are, but smaller.

**Comment by gvilarino** [comment]
@jaakkokorhonen movement hadn't been happening on the guanyem fork because Gerald hadn't updated from upstream and I got push/pull permissions just yesterday.

@jayapapaya I'm working with toret and team on a daily basis, and getting all functionality they need in the app.

I can't promise to deliver on design so I'll focuse on making it work. Making it _nice_ is a nice-to-have, not a must-have.

**Comment by jayapapaya** [comment]
@gvilarino  ok - look, tried to make some basic styles as easy and quick as possible (https://github.com/d-cent/patterns/labels/dos). will leave this now, as it seems to only be confusing things rather than help. 

will just carry on working on the styleguide - ping me if there is anything guanyem related that I can help with. (again, in case you didn't catch it, the guanyem svg logo is in slack).

**Comment by gvilarino** [comment]
Thanks @jayapapaya; they won't be using a logo since the pilot is to run in a multi-party event and therefore they can't show their own logo without showing them all.

**Comment by jayapapaya** [comment]
@gvilarino  - yeah, Toret told me that they will not be using the guanyem logo. I have made an svg with their other design for the governar obeint. A link for it is here: https://github.com/d-cent/patterns/issues/37

**Comment by jaakkokorhonen** [comment]
If this is done, @jayapapaya maybe close it?
