### ISSUE TITLE
init.d daemon needed

### ISSUE THREAD

**Issue by geraldo** [d-cent/democracyos#53]
the problem is that I don't know which binary to star, shouldn't it be bin/dos-run?

**Comment by gvilarino** [comment]
This is all explained in our [official wiki](https://github.com/DemocracyOS/app/wiki/Installation#running)

**Comment by geraldo** [comment]
ok, I explained myself wrong, we need to run it as a service (Debian 7, sysvinit). finally we did it similar to this guide: https://github.com/ether/etherpad-lite/wiki/How-to-deploy-Etherpad-Lite-as-a-service
