### ISSUE TITLE
D-CENT misspelled in http://democracyos-dcent.herokuapp.com/

### ISSUE THREAD

**Issue by jaakkokorhonen** [d-cent/democracyos#61]
![screenshot 2014-12-05 14 16 21](https://cloud.githubusercontent.com/assets/3482497/5315680/6624b7a4-7c89-11e4-986b-a14890875754.png)

@gvilarino where to change this?

**Comment by gvilarino** [comment]
this is set in the `ORGANIZATION_NAME` environment variable

**Comment by gvilarino** [comment]
Fixed in both [the live demo](http://democracyos-dcent.herokuapp.com/) and the [finnish pilot](http://finnish-democracyos.herokuapp.com/) environments
