### ISSUE TITLE
Add D-CENT favicon 

### ISSUE THREAD

**Issue by jayapapaya** [d-cent/democracyos#65]
This: https://www.dropbox.com/s/p7u7nq24o5xq1qz/favicon.png?dl=0

for both 
http://finnish-democracyos.herokuapp.com/
and
http://democracyos-dcent.herokuapp.com/

@saariokari ?
or @gvilarino ?

**Comment by gvilarino** [comment]
The `?dl=0` shouldn't be a part of the querystring to an image URL in the config.

BTW this is set in the `FAVICON` env variable.

**Comment by gvilarino** [comment]
@jayapapaya that URL won't do for DemocracyOS since it isn't the direct link to the file; the underlying URL is https://dl.dropboxusercontent.com/content_link/LNs4WeOzdFbbaGMFSJ2Py2rK6KwRG0N5hZ8T83vsHY6cyBAEadsd7qIpFSSYj8wz

Be careful when linking to dropbox ;)

**Comment by jayapapaya** [comment]
@gvilarino oops ;) 
here: https://raw.githubusercontent.com/d-cent/patterns/master/source/assets/img/favicon.png

**Comment by gvilarino** [comment]
@jayapapaya but githubusercontent.com has client throttling so I wouldn't rely on it for a client. I'll append the file to the codebase and it can later be uploaded to a CDN solution.
